spring:
  datasource:
    url: jdbc:mysql://192.168.1.102:3306/springcloud?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: "0000"
  jpa:
    show-sql: true
    generate-ddl: true
    database: mysql
